### ISSUE TITLE
Carousel - Keyboard interaction question

### ISSUE THREAD

**Issue by greenc05** [bbc/a11y-tutorials#17]
With regards to list item 3 for ‘Keyboard Interaction’ in the tutorial:

https://bbc.github.io/a11y-tutorials/carousel/ 

‘...When a card appears that they wish to click, they can move back into the card area with Shift + Tab.’ 

Is the idea that new card content is automatically announced when the 'Next' button is activated @Heydon? If not how does the user know that a card has appeared that they wish to click?

If it's not automatically announced, I am unsure that this is the best UX? Instead should we move focus to the first focusable item within the new card that is now visible? No doubt, you didn't do that for a good reason?

**Comment by Heydon** [comment]
@greenc05 Yes, this is deliberate and not an oversight. The buttons are labeled to indicate they 'load' more cards. There is no need for an announcement and we would want to avoid moving the user's focus under their feet. 

The idea is that there is parity between different users' experience. Where IntersectionObserver is successfully incorporated, only the visible cards should be interactive.

**Comment by greenc05** [comment]
Thanks for confirming @Heydon
